/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.byohttp;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.File;

public class ByoHttpTest {

    @Test
    @DisplayName("When constructing ByoHttp given port and resources path then return a new instance")
    public void testApp() {
        new ByoHttp(1234, new File("/var/www"), new File("/resources/MIMETypes.csv"));
        // no exception thrown
    }
}
